### PR TITLE
fix ReferenceError: window is not defined

### PR DESCRIPTION
**Pull request by DimaRGB**
- bug report: https://github.com/webpack/webpack/issues/6522
- more details: https://github.com/webpack/webpack/issues/6525
- get solution from this comment: https://github.com/webpack/webpack/issues/6525#issuecomment-491268897

### CODE REVIEW

**Comment by DimaRGB** [comment]
@CharlesStover please review ASAP :)

**Comment by quisido** [comment]
Can you add a unit test (that would fail in the current repository) to show the problem being fixed now?

e.g. a unit test where `window` does not exist in the environment, but `react-innertext` still works.

**Comment by DimaRGB** [comment]
@CharlesStover added.

Tested for the previus build, were failed.
But for new build, passed.

**Comment by quisido** [comment]
Thank you. :)
Great work.

**Pull request merged**
